### PR TITLE
(feat): updated texts cases, fixed some typos, etc.

### LINKED ISSUE #62: [Task] content: update texts and fix typos cases page
### Area / component

Content

### Task description

On the cases page some of the texts could do with a bit more flare, and typos need to be fixed (e.g., 1801 > Improvements > first occurrence of "team" should be "time"). Also projects might have moved ahead, etc.

Should put an alarm or workflow somewhere so we do this once every X months (3?).

### Subtasks (checklist)

_No response_

### Due date (optional)

_No response_

### Dependencies / related issues

_No response_

### References / resources

```markdown

```

### Definition of Done

- [ ] Work completed
- [ ] Verified by reviewer/stakeholder

### PR DESCRIPTION
**Pull request by sjorsieporsie**
Fix #62. See code bellow for more info

### CODE REVIEW

File: src/pages/Cases.tsx [hunk 1]
```diff
@@ -157,8 +157,8 @@ export function CasesPage() {
         <button
           className="cursor-pointer rounded-full bg-white px-4 py-2 font-semibold transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:shadow-white/50 sm:w-fit"
           onClick={() =>
-            (window.location.href =
```
Comment (mateiAvram) [inline src/pages/Cases.tsx]: what exactly was changed here?

**Review by mateiAvram — COMMENTED** [review]
Please have a look at the comments I made throughout the code
